version: "3.7"
services:
  backend:
    build: ./flask
    container_name: my-running-flask-app
    ports:
      - "8003:5000"
    volumes:
      - "./flask:/mnt/sda4/jffs/my-video-app/flask"
  frontend:
    build: ./frontend
    container_name: my-running-react-app
    ports:
      - "3003:3000"
    volumes:
      - "./frontend:/usr/src/app"