version: "3.7"
services:
  backend:
    build: ./flask
    container_name: my-running-flask-app
    ports:
      - "8003:5000"
    volumes:
      - "./flask:/mnt/sda4/jffs/my-video-app/flask"
      - "./static/adults:/mnt/sda4/data/AI"
      - "./static/kids:/mnt/sda4/data/kids"
  frontend:
    build: ./react
    container_name: my-running-react-app
    ports:
      - "3003:3000"
    volumes:
      - "./react:/usr/src/app"
      - /usr/src/app/node_modules
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./static/adults:/mnt/sda4/data/AI"
      - "./static/kids:/mnt/sda4/data/kids"
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - backend
      - frontend