FROM python:3.6

RUN apt update
RUN apt install -y ffmpeg

WORKDIR /mnt/sda4/jffs/my-video-app/flask

COPY ./requirements.txt /mnt/sda4/jffs/my-video-app/flask/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . /mnt/sda4/jffs/my-video-app/flask/
