"""empty message

Revision ID: c654d179274c
Revises: 9bc1259c228b
Create Date: 2022-06-20 12:02:36.726782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c654d179274c'
down_revision = '9bc1259c228b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('media') as batch_op:
        batch_op.drop_column('width')
        batch_op.drop_column('height')
