"""empty message

Revision ID: c9f95e57df4b
Revises: 3d7f78765af2
Create Date: 2021-05-11 02:28:12.891965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f95e57df4b'
down_revision = '3d7f78765af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('android_release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=True),
    sa.Column('version_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_android_release_id'), 'android_release', ['id'], unique=False)
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_index(op.f('ix_android_release_id'), table_name='android_release')
    op.drop_table('android_release')
    # ### end Alembic commands ###
